[project]
name = "poker-python-project"
version = "0.1.0"
description = "A project to practice data analysis techniques on the game of poker."
readme = "README.md"
requires-python = ">=3.14"
dependencies = []
[project.optional-dependencies]
dev = [
    "black",
    "flake8",
    "flake8-black",
    "flake8-pyproject",
    "pytest",
    "pylint",
    "isort",
    "mypy",
]
[tool.black]
line-length = 88
[tool.flake8]
max-line-length = 88
[tool.setuptools.package-data]
"poker_python_project.data" = ["*.json"]
