from poker_python_project.app.card import Card as Card
from typing import Deque

class Deck:
    cards: Deque[Card]
    remaining: Deque[Card]
    taken: Deque[Card]
    discarded: Deque[Card]
    def __init__(self, shuffled: bool = True) -> None: ...
    def draw(self, number: int = 1) -> Deque[Card]: ...
    def mill(self, number: int = 1) -> Deque[Card]: ...
    def peek(self, number: int = 1) -> Deque[Card]: ...
    def recycle(self, shuffled: bool = True) -> bool: ...
