from collections import deque

class Deck:
    cards: deque
    symbols: dict
    remaining: deque
    taken: deque
    discarded: deque
    def __init__(self, shuffled: bool = True) -> None: ...
    def draw(self, number: int = 1) -> deque[str]: ...
    def mill(self, number: int = 1) -> deque[str]: ...
    def peek(self, number: int = 1) -> deque[str]: ...
    def recycle(self, shuffled: bool = True) -> bool: ...
