from poker_python_project.app.card import Card as Card
from poker_python_project.app.deck import Deck as Deck
from typing import Deque

class Hand:
    def __init__(self, draw_from: Deck) -> None: ...
    def check(self, card: Card) -> bool: ...
    def discard(self, card: Card) -> None: ...
    def draw(self, number: int) -> Deque[Card]: ...
    def show(self) -> Deque[Card]: ...
    def play(self, card: Card, removed: bool = True) -> Card | None: ...
