from collections import deque
from poker_python_project.app.deck import Deck as Deck

class Hand:
    def __init__(self, draw_from: Deck) -> None: ...
    def check(self, card: str) -> bool: ...
    def discard(self, card: str) -> None: ...
    def draw(self, number: int) -> deque[str]: ...
    def show(self) -> deque[str]: ...
    def play(self, card: str, removed: bool = True) -> str | None: ...
